Repository Johny1010/WDP-1909-01, pull requests merged in 2019-10, with the labels that each got.

#7 Wdp190901 5
  .DS_Store
  src/index.html
  src/partials/50_section-products.html
  src/sass/_variables.scss
  src/sass/components/_button.scss
  src/sass/components/_post-box.scss
  src/sass/components/_product-box.scss
  src/sass/style.scss
  src/scripts/app.js
Labels: Changes requested

#8 change for button Quick view and Add to cart + price background on hover
  .DS_Store
  package-lock.json
  src/sass/components/_button.scss
  src/sass/components/_product-box.scss
Labels: Changes requested

#6 bug-WDP190901-3
  src/partials/30_section-features.html
  src/sass/components/_feature-box.scss
Labels: Changes requested, question

#9 change select to ul>li, add styles in _header.scss
  src/partials/10_header.html
  src/sass/components/_header.scss
Labels: To review

#19 add responsive Latest Blog
  src/partials/70_section-blog-posts.html
Labels: To review

#29 Wdp190901 21
  src/index.html
  src/partials/10_header.html
  src/partials/20_home.html
  src/partials/80_section-feedback.html
  src/sass/components/_button.scss
  src/sass/components/_header.scss
  src/sass/components/_home.scss
  src/sass/components/_section--feedback.scss
  src/sass/style.scss
Labels: To review

#22 Zadanie-WDP190901-17
  src/index.html
  src/partials/50_section-products.html
  src/sass/components/_product-box.scss
  src/sass/style.scss
  src/scripts/app.js
Labels: To review

#32 task-WDP190901-25
  src/sass/components/_section-markup.scss
Labels: To review

#13 add media queries for tablet and mobile in _product-box.scss
  src/sass/components/_product-box.scss
Labels: To review
